// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateQuizController from "./create_quiz_controller"
application.register("create-quiz", CreateQuizController)

import GoogleOauthController from "./google_oauth_controller"
application.register("google-oauth", GoogleOauthController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
